---
abstract: 'Anki note generation made easy.'
author:
  - 'Steve Dondley <s@dondley.com>'
build_requires:
  Carp: '0'
  Modern::Perl: '0'
  Test::Exception: '0'
  Test::More: '0'
  Test::Warnings: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Anki-Import
requires:
  Cwd: '0'
  Data::Dumper: '0'
  Exporter: '0'
  Getopt::Args: '0'
  Log::Log4perl::Shortcuts: '0'
  Path::Tiny: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/sdondley/Anki-Import/issues
  repository: git://github.com/sdondley/Anki-Import.git
version: '0.007'
x_generated_by_perl: v5.24.4
x_serialization_backend: 'YAML::Tiny version 1.70'
